# Configuration Netlify pour mycontacts
[build]
  # Dossier contenant l'application React à déployer
  base = "client/"
  
  # Commande pour construire l'application React
  command = "npm run build"
  
  # Dossier contenant les fichiers statiques générés
  publish = "build/"

# Variables d'environnement pour le build
[build.environment]
  REACT_APP_API_URL = "https://mycontacts-k14l.onrender.com/api"

# Redirections pour le routing côté client React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
